### ISSUE TITLE
Traduire tfa/tcoa.json

### ISSUE THREAD

**Issue by kamiben** [kamiben/arkhamdb-json-data#23]

**Comment by kamiben** [comment]
tcoa.json est à jour avec les données US, plus qu'à traduire

**Comment by kamiben** [comment]
Fichier traduit

**Comment by Fabrice2** [comment]
Bien joué !!!
Tu as été rapide 😁

Moi je suis en train de peindre les portes de salle de bain et chambre d’en
bas du chalet
