### ISSUE TITLE
FR : traduire les cartes de campagne

### ISSUE THREAD

**Issue by kamiben** [kamiben/arkhamdb-json-data#30]
- [x] 	Abbess Allegria Di Biase
- [x] 	Alejandro Vela
- [x] 	Bauta
- [x] 	Clasp of Black Onyx
- [x] 	Dr. Francis Morgan
- [x] 	Dr. Henry Armitage
- [x] 	Earl Sawyer
- [x] 	Expedition Journal
- [x] 	Gavriella Mizrah
- [x] 	Gilded Volto
- [x] 	Ichtaca
- [x] 	Jerome Davids
- [x] 	Lady Esprit
- [x] 	Lita Chantler
- [x] 	Medico Della Peste
- [x] 	Monstrous Transformation
- [x] 	Naomi O'Bannion
- [x] 	Pantalone
- [x] 	Penny White
- [x] 	Powder of Ibn Ghazi
- [x] 	Professor Warren Rice
- [x] 	Puzzle Box
- [x] 	Relic of Ages
- [x] 	Relic of Ages
- [x] 	Relic of Ages
- [x] 	Relic of Ages
- [x] 	The Black Book
- [x] 	The Necronomicon
- [x] 	The Tattered Cloak
- [x] 	Valentino Rivas
- [x] 	Zebulon Whateley
- [x] 	The Man in the Pallid Mask
- [x] 	Across Space and Time
- [x] 	Curse of the Rougarou
- [x] 	Lost Soul
- [x] 	Out of Body Experience
- [x] 	Poisoned

**Comment by kamiben** [comment]
Je n'ai pas les cartes des packs optionnels en FR (Rougarou, Carnaval) ... a voir si on les récupère.

**Comment by kamiben** [comment]
Ne reste que les cartes que je ne possède pas en FR

**Comment by Blader67** [comment]
Normalement j'ai tout fait...

**Comment by kamiben** [comment]
Merci @Blader67 ;)
